### ISSUE TITLE
StarUML supports SysML, UML, and how to make it also support UPDM（DoDAF2）

### ISSUE THREAD

**Issue by Iyetux** [staruml/staruml-xmi#19]
StarUML supports SysML, UML, and how to make it also support UPDM（DoDAF2）。

There is too little information in this regard. But I want to implement a plug-in of StarUML, which has the modeling ability of DoDAF.

However, I don't know how to start.

**Comment by escribis** [comment]
Bonjour lyetux,
Here is an quick answer that might help, before an official answer from the StarUML team.
StarUML do allow you to define profiles, so I guess that in principle you can implement UPDM. However the devil is in the details and you will have to check if the features you need are available in the SysML and UML metamodels (which are not stricly compliant to the standards. Discrepancies exist in all modeling tools).0

 Since there is no ready-to use UPDM extension for StarUML you will have to define the profile https://docs.staruml.io/working-with-uml-diagrams/profile-diagram . This is not easy since you will have to check the existing StarUML metamodel (hundreds of classes, just like in other modeling tools). The metamodel is available in this repository : https://github.com/staruml/staruml-samples
StarUML allows you do define a profule, but this is not an easy task (just like in any other tools). 

Hope this helps.

Regards
      Jean-marie

**NOTE: Instead of using this channel (the xmi repository is not linked to your question, so you might not receive answers), this question must go in google group forum : https://groups.google.com/g/staruml  It would be cool if you duplicate the question there so that the questions/anwsers will placed in the right place.**
